### ISSUE TITLE
Some cleanup

### ISSUE THREAD

**Issue by YaredDejene** [betsegaw-degefe/BuyAndSell#1]
Please remove your the following files and folders from your repository and stop them tracking by just including them in your gitignore file. 

BuyAndSellApi/.vscode
BuyAndSellApi/.idea/.idea.BuyAndSellApi
BuyAndSellApi/bin
BuyAndSellApi/obj
BuyAndSell.DotSettings.user
BuyAndSellApi.DotSettings.user

**Comment by YaredDejene** [comment]
Avoid including magic strings in your code e.g. connection strings, you have appsettings.json to store such king of values.

**Comment by betsegaw-degefe** [comment]
Thank you @YaredDejene! All of your comment are helpful. I will add them in the gitignore.
