### ISSUE TITLE
Magic strings

### ISSUE THREAD

**Issue by YaredDejene** [betsegaw-degefe/BuyAndSell#2]
Avoid including magic strings in your code e.g. connection strings, you have appsettings.json to store such king of values.

**Comment by betsegaw-degefe** [comment]
Thank you, I will correct based your comment.

**Comment by betsegaw-degefe** [comment]
> Avoid including magic strings in your code e.g. connection strings, you have appsettings.json to store such king of values.

**Comment by betsegaw-degefe** [comment]
Thank you, I will avoid them.
