### ISSUE TITLE
Naming 

### ISSUE THREAD

**Issue by YaredDejene** [betsegaw-degefe/BuyAndSell#3]
Be consistent in naming your files and classes. e.g. buyandsellContext.cs.  You can follow these standards and naming conventions, [C# Coding Standards and Naming Conventions](https://github.com/ktaranov/naming-convention/blob/master/C%23%20Coding%20Standards%20and%20Naming%20Conventions.md)

**Comment by betsegaw-degefe** [comment]
Thank you for taking a time to review my code. I will correct naming based on the standard.
