### ISSUE TITLE
EF Core FluentAPI 

### ISSUE THREAD

**Issue by YaredDejene** [betsegaw-degefe/BuyAndSell#4]
In your DB context, I see a long list of EF Core FluentAPI definitions to map your db tables with the entities. But you can define those configs using attributes like [Table], [Column], and [ForeignKey] on top of your entity classes and properties. Use FluentAPI when you need to configure domain classes to override conventions

**Comment by yido** [comment]
Good comments

**Comment by betsegaw-degefe** [comment]
Thank you @YaredDejene for your great comment. I will Improve that.
